name: Make build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Install NASM and BBE
      run: sudo apt-get update && sudo apt-get install nasm bbe
    - name: Checkout code
      uses: actions/checkout@v4
    - name: make
      run: make
    - name: Upload raw disk image
      uses: actions/upload-artifact@v4
      with:
        name: disk.img
        path: build/disk.img
