name: Make build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Install NASM
      uses: mstksg/get-package@v1
      with:
        apt-get: nasm
    - name: Install BBE
      uses: mstksg/get-package@v1
      with:
        apt-get: bbe
    - name: Checkout code
      uses: actions/checkout@v2
    - name: 'CI patch: remove linker size constraints'
      run: sed -Ei 's/, LENGTH = [0-9]*k//' linker.ld
    - name: make
      run: make
